behaviors:
  MovetoGoal:
    trainer_type: ppo
    hyperparameters:
       batch_size: 256
       buffer_size: 1024
       learning_rate: 0.0003
       beta: 0.005
       epsilon: 0.2
       lambd: 0.95
       num_epoch: 3
       learning_rate_schedule: linear
    checkpoint_interval: 10000
    keep_checkpoints: 5 
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.5
        demo_path: Demos/movetogol.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/movetogol.demo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000

  MagCoop:
    trainer_type: ppo
    hyperparameters:
       batch_size: 256
       buffer_size: 1024
       learning_rate: 0.0003
       beta: 0.005
       epsilon: 0.2
       lambd: 0.95
       num_epoch: 3
       learning_rate_schedule: linear
    checkpoint_interval: 10000
    keep_checkpoints: 5 
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.5
        demo_path: Demos/movetogol.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/movetogol.demo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000