behaviors:
  MagCoop:
    trainer_type: ppo
    hyperparameters:
       batch_size: 128
       buffer_size: 512
       learning_rate: 0.0003
       beta: 0.008
       epsilon: 0.2
       lambd: 0.95
       num_epoch: 3
       learning_rate_schedule: linear
    checkpoint_interval: 10000
    keep_checkpoints: 5 
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000